= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2019/20
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von:** Leon Augustat

**Gruppe:** 35

== Was habe ich gelernt?
// Ausführung der positiven und negativen Erfahrungen, die im Softwarepraktikum gesammelt wurden.
Im Praktikum habe ich gelernt, wie man Schritt für Schritt eine Software entwickelt. Besonders in der Entwicklungsphase konnte ich mir beibringen, wie man Probleme, wie zum Beispiel Errors und generelle Implementierungsfehler, besser und schneller lösen kann. Desweiteren konnte ich meine Fähigkeiten im Umgang mit externen Frameworks und Spring verbessern.

== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?
Die Zusammenarbeit im Team fande ich sehr gut. Jedem Teammitglied wurde eine Komponente zugeordnet, an die er arbeiten sollte. Auch durch das Anlegen von Issues auf github hatte man einen guten Überblick, wie weit die anderen Teammitglieder in der Woche vorangekommen sind. Man hat sich auch gut verstanden. Falls jemand Probleme oder Fragen hatte, wurde ihm schnell geholfen.

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was War gut? Was war verbesserungswürdig?
Den Einstieg in Salespoint fande ich zu Beginn des Praktikums schwierig. Nachdem ich mich jedoch intensiv eingelesen habe, konnte ich gut mit Salespoint, aber auch mit anderen Frameworks arbeiten, jedoch war es nicht immer nötig, Salespoint zu verwenden.

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
// Möglichst mit Beschreibung, warum die Umsetzung des von Ihnen angebrachten Vorschlages nötig ist.
Die Gruppen sollte man selbst zusammenstellen können, da man sich schon kennt und die Kommunikation dadurch schon von Beginn an gut läuft.

== Feedback für den Tutor
// Fühlten Sie sich durch den vom Lehrstuhl bereitgestellten Tutor gut betreut? Was war positiv? Was war verbesserungswürdig?
Mit unserem Tutor bin ich im Gesamten ebenfalls zufrieden. Er hat auf Fragen schnell geantwortet, hat die nächsten Aufgaben bei jedem Standup-Meeting verständlich erklärt und 

== Sonstiges und Anmerkungen
// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?
